name: sqlite_flutter_crud
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+8
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  http: ^1.2.1
  provider: ^6.1.2
  loading_indicator: ^3.1.1
  cached_network_image: ^3.4.0
  flutter_secure_storage: ^9.2.2
  firebase_storage: ^12.2.0
  firebase_core: ^3.4.0
  file_picker: ^8.0.5
  google_maps_flutter: ^2.1.1
  firebase_app_check: ^0.3.1
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  permission_handler: ^11.3.1
  device_info: ^2.0.3
  disk_space: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/assets/mamba_verde.jpg
    - lib/assets/mamba_negra.jpg
    - lib/assets/Villavicencio.jpg
