// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKMOjsVFJNBIMQjWGk_aZ1gV1u2IGV67Y',
    appId: '1:766715754129:web:ff4b3c7027be77a03cf130',
    messagingSenderId: '766715754129',
    projectId: 'meta-snake',
    authDomain: 'meta-snake.firebaseapp.com',
    storageBucket: 'meta-snake.appspot.com',
    measurementId: 'G-MQM7ZZGW6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWHBqhaA7C02IBRZHosb92kq0L0azHQCY',
    appId: '1:766715754129:android:f20d009a47dc84f03cf130',
    messagingSenderId: '766715754129',
    projectId: 'meta-snake',
    storageBucket: 'meta-snake.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpTvugFdbCuhvqNwEiJzeTjH_0tPiOmc',
    appId: '1:766715754129:ios:b30c72227fcf887b3cf130',
    messagingSenderId: '766715754129',
    projectId: 'meta-snake',
    storageBucket: 'meta-snake.appspot.com',
    iosBundleId: 'com.example.sqliteFlutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpTvugFdbCuhvqNwEiJzeTjH_0tPiOmc',
    appId: '1:766715754129:ios:b30c72227fcf887b3cf130',
    messagingSenderId: '766715754129',
    projectId: 'meta-snake',
    storageBucket: 'meta-snake.appspot.com',
    iosBundleId: 'com.example.sqliteFlutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKMOjsVFJNBIMQjWGk_aZ1gV1u2IGV67Y',
    appId: '1:766715754129:web:24ba60dac2b626a93cf130',
    messagingSenderId: '766715754129',
    projectId: 'meta-snake',
    authDomain: 'meta-snake.firebaseapp.com',
    storageBucket: 'meta-snake.appspot.com',
    measurementId: 'G-DW2NW43H3D',
  );
}
